---
name: Request review
"on":
  pull_request:
    types: ['opened']
jobs:
  assist-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: g4s8/review-assistant@master
        with:
          reviewers: 'g4s8'
          assignees: 'g4s8'
          labels: 'scope/pr,review-assistant'
          token: '${{ secrets.GITHUB_TOKEN }}'
